  python -m lerobot.record \
    --robot.type=franka_fer \
    --robot.server_ip=192.168.18.1 \
    --robot.server_port=5000 \
    --teleop.type=vr \
    --teleop.tcp_port=8000 \
    --teleop.verbose=false \
    --dataset.fps=30 \
    --dataset.episode_time_s=10 \
    --dataset.num_episodes=1 \
    --dataset.root=./datasets/dummy \
    --dataset.repo_id=your_username/franka_vr_test \
    --dataset.single_task="Test VR teleoperation data collection"